spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/prod_db

  graphql:
    schema:
      locations: classpath:schema

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/