spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/prod_db
    username: aymane
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: "init"
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 8083
